package com.pojo;
// Generated Mar 4, 2018 12:55:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Student generated by hbm2java
 */
@Entity
@XmlRootElement
public class Student implements java.io.Serializable {

    @Id
    @GeneratedValue
    private Integer id;
    private String name;
    private String dob;
    private String email;
    private String password;
    private String address;
    private String gender;
    private String contact;
    private String city;
    private String course;

    public Student() {
    }

    public Student(String name, String dob, String email, String password, String address, String gender, String contact, String city, String course) {
        this.name = name;
        this.dob = dob;
        this.email = email;
        this.password = password;
        this.address = address;
        this.gender = gender;
        this.contact = contact;
        this.city = city;
        this.course = course;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDob() {
        return this.dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCourse() {
        return this.course;
    }

    public void setCourse(String course) {
        this.course = course;
    }

}
